/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IST_411_GIT;

import java.awt.Frame;

/**
 *
 * @author Steven
 */
public class add_restaurant_information extends javax.swing.JFrame {
    /**
     * Creates new form add_restaurant_information1
     */
    public add_restaurant_information() {
        initComponents();
        setStates();
        setCategories();
        
    }
    private String strState;
    private String strCategory;
    //Puts local state abbreviation values into States Combobox
    private void setStates()
    {
        String[] aryStates = {"AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA",
                                    "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH",
                                    "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX",
                                    "UT", "VT", "VA", "WA", "WV", "WI", "WY"};
        for (String strAdd: aryStates)
        {
            jcbStates.addItem(strAdd);
        }
    }
    //Puts food category values from the database into the categories Combobox.
    private void setCategories()
    {
        String categories_result = FUNCTIONS.INTERFACE_REQUEST("1400");
        String[] categories = categories_result.split("%\\|%");
        for(int rcategory_counter = 0; rcategory_counter < categories.length; rcategory_counter++){
            String[] category_information = categories[rcategory_counter].split("\\|");
            
            jcbCategories.addItem (category_information[1]);
        }

    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfPhone = new javax.swing.JTextField();
        jlAddress2 = new javax.swing.JLabel();
        jlPhone = new javax.swing.JLabel();
        jtfAddressLine1 = new javax.swing.JTextField();
        jtfCity = new javax.swing.JTextField();
        jlFoodCategories = new javax.swing.JLabel();
        jtfZip = new javax.swing.JTextField();
        jcbStates = new javax.swing.JComboBox();
        jlAddress1 = new javax.swing.JLabel();
        jlCity = new javax.swing.JLabel();
        jlZip = new javax.swing.JLabel();
        jtfRestaurantName = new javax.swing.JTextField();
        jlState = new javax.swing.JLabel();
        jlRestaurantName = new javax.swing.JLabel();
        jtfAddressLine2 = new javax.swing.JTextField();
        jbAddRestaraunt = new javax.swing.JButton();
        jcbCategories = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlAddress2.setText("Address Line 2:");

        jlPhone.setText("Phone:");

        jlFoodCategories.setText("Food Categories");

        jcbStates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbStatesActionPerformed(evt);
            }
        });

        jlAddress1.setText("Address Line 1:");

        jlCity.setText("City:");

        jlZip.setText("Zip Code:");

        jlState.setText("State:");

        jlRestaurantName.setText("Restaurant Name:");

        jbAddRestaraunt.setText("Add Restaurant");
        jbAddRestaraunt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddRestarauntActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlRestaurantName)
                                    .addComponent(jlPhone)
                                    .addComponent(jlAddress1)
                                    .addComponent(jlAddress2)
                                    .addComponent(jlCity))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfRestaurantName, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                                    .addComponent(jtfAddressLine1)
                                    .addComponent(jtfAddressLine2)
                                    .addComponent(jtfPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfCity)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlFoodCategories)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(49, 49, 49)
                                            .addComponent(jlZip))
                                        .addComponent(jlState, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jcbStates, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jcbCategories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtfZip, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jbAddRestaraunt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfRestaurantName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlRestaurantName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPhone))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfAddressLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlAddress1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfAddressLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlAddress2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCity))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbStates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlState))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlZip)
                    .addComponent(jtfZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlFoodCategories)
                    .addComponent(jcbCategories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(168, 168, 168)
                .addComponent(jbAddRestaraunt, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbStatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbStatesActionPerformed

    }//GEN-LAST:event_jcbStatesActionPerformed

    private void jbAddRestarauntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddRestarauntActionPerformed
        //Gets string value of States Combobox.
        strState = String.valueOf(jcbStates.getSelectedItem());
        //Gets string value of Categories Combobox.
        strCategory = String.valueOf(jcbCategories.getSelectedItem());
        //Gets Text Values of input components and sends to database.
        FUNCTIONS.INTERFACE_REQUEST("1300", "name", jtfRestaurantName.getText(), "phone", jtfPhone.getText(), "address_line_1", jtfAddressLine1.getText(), "address_line_2", jtfAddressLine2.getText(), "city", jtfCity.getText(), "state", strState, "zip_code", jtfZip.getText(), "food_category", strCategory);
    }//GEN-LAST:event_jbAddRestarauntActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_restaurant_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_restaurant_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_restaurant_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_restaurant_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_restaurant_information().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAddRestaraunt;
    private javax.swing.JComboBox jcbCategories;
    private javax.swing.JComboBox jcbStates;
    private javax.swing.JLabel jlAddress1;
    private javax.swing.JLabel jlAddress2;
    private javax.swing.JLabel jlCity;
    private javax.swing.JLabel jlFoodCategories;
    private javax.swing.JLabel jlPhone;
    private javax.swing.JLabel jlRestaurantName;
    private javax.swing.JLabel jlState;
    private javax.swing.JLabel jlZip;
    private javax.swing.JTextField jtfAddressLine1;
    private javax.swing.JTextField jtfAddressLine2;
    private javax.swing.JTextField jtfCity;
    private javax.swing.JTextField jtfPhone;
    private javax.swing.JTextField jtfRestaurantName;
    private javax.swing.JTextField jtfZip;
    // End of variables declaration//GEN-END:variables
}
