/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IST_411_GIT;

import java.awt.Component;
import java.awt.Frame;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Steven
 */
public class add_restaurant_information extends javax.swing.JFrame {
    /**
     * Creates new form add_restaurant_information1
     */
    public add_restaurant_information() {
        initComponents();
        setStates();
        setCategories();
        
    }
    private String strState;
    private String strCategory;
    //Puts local state abbreviation values into States Combobox
    private void setStates()
    {
        String[] aryStates = {"AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA",
                                    "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH",
                                    "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX",
                                    "UT", "VT", "VA", "WA", "WV", "WI", "WY"};
        for (String strAdd : aryStates)
        {
            jcbStates.addItem(strAdd);
        }
    }
    //Puts food category values from the database into the categories Combobox.
    private void setCategories()
    {
        String categories_result = FUNCTIONS.INTERFACE_REQUEST("1400");
        String[] categories = categories_result.split("%\\|%");
        for(int rcategory_counter = 0; rcategory_counter < categories.length; rcategory_counter++){
            String[] category_information = categories[rcategory_counter].split("\\|");
            
            jcbCategories.addItem (category_information[1]);
        }

    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfPhone = new javax.swing.JTextField();
        jlAddress2 = new javax.swing.JLabel();
        jlPhone = new javax.swing.JLabel();
        jtfAddressLine1 = new javax.swing.JTextField();
        jtfCity = new javax.swing.JTextField();
        jlFoodCategories = new javax.swing.JLabel();
        jtfZip = new javax.swing.JTextField();
        jcbStates = new javax.swing.JComboBox();
        jlAddress1 = new javax.swing.JLabel();
        jlCity = new javax.swing.JLabel();
        jlZip = new javax.swing.JLabel();
        jtfRestaurantName = new javax.swing.JTextField();
        jlState = new javax.swing.JLabel();
        jlRestaurantName = new javax.swing.JLabel();
        jtfAddressLine2 = new javax.swing.JTextField();
        jbAddRestaraunt = new javax.swing.JButton();
        jcbCategories = new javax.swing.JComboBox();
        jbCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlAddress2.setText("Address Line 2:");

        jlPhone.setText("*Phone:");

        jlFoodCategories.setText("Food Category:");

        jcbStates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbStatesActionPerformed(evt);
            }
        });

        jlAddress1.setText("*Address Line 1:");

        jlCity.setText("*City:");

        jlZip.setText("*Zip Code:");

        jlState.setText("*State:");

        jlRestaurantName.setText("*Restaurant Name:");

        jbAddRestaraunt.setText("Add Restaurant");
        jbAddRestaraunt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddRestarauntActionPerformed(evt);
            }
        });

        jbCancel.setText("Back");
        jbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbAddRestaraunt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlRestaurantName)
                    .addComponent(jlCity)
                    .addComponent(jlAddress1)
                    .addComponent(jtfRestaurantName, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPhone)
                    .addComponent(jtfPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfAddressLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlAddress2)
                    .addComponent(jtfAddressLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCity, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlState)
                            .addComponent(jcbStates, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfZip, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlZip)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlFoodCategories)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlRestaurantName)
                .addGap(1, 1, 1)
                .addComponent(jtfRestaurantName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlPhone)
                .addGap(1, 1, 1)
                .addComponent(jtfPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlAddress1)
                .addGap(1, 1, 1)
                .addComponent(jtfAddressLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlAddress2)
                .addGap(3, 3, 3)
                .addComponent(jtfAddressLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlCity)
                .addGap(1, 1, 1)
                .addComponent(jtfCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlState)
                    .addComponent(jlZip))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbStates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbCategories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlFoodCategories))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jbAddRestaraunt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jbCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbStatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbStatesActionPerformed

    }//GEN-LAST:event_jcbStatesActionPerformed

    //When activated checks input values and inserts values into database.
    private void jbAddRestarauntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddRestarauntActionPerformed
        //Gets string value of States Combobox.
        strState = String.valueOf(jcbStates.getSelectedItem());
        //Gets string value of Categories Combobox.
        strCategory = String.valueOf(jcbCategories.getSelectedItem());
        
        //Checks if required fields are null and requests input if they are.
        Component frame = null;
        if (jtfRestaurantName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(frame, "Please enter a Restaurant Name.");
            return;
        }
        if (jtfPhone.getText().equals(""))
        {
            JOptionPane.showMessageDialog(frame, "Please enter a Phone Number.");
            return;
        }
        if (jtfAddressLine1.getText().equals(""))
        {
            JOptionPane.showMessageDialog(frame, "Please enter an Address.");
            return;
        }        
        if (jtfCity.getText().equals(""))
        {
            JOptionPane.showMessageDialog(frame, "Please enter a City.");
            return;
        }
        if (jtfZip.getText().equals(""))
        {
            JOptionPane.showMessageDialog(frame, "Please enter a Zip Code.");
            return;
        }
        

        //Gets Text Values of input components and sends to database        
        FUNCTIONS.INTERFACE_REQUEST("1300", "name", jtfRestaurantName.getText(), "phone", jtfPhone.getText(), "address_line_1", jtfAddressLine1.getText(), "address_line_2", jtfAddressLine2.getText(), "city", jtfCity.getText(), "state", strState, "zip_code", jtfZip.getText(), "food_category", strCategory);
        JOptionPane.showMessageDialog(this, "Restaurant was added");
        JFrame main = new main();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbAddRestarauntActionPerformed
    
    //Closes window back to Main without a database entry.
    private void jbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelActionPerformed
        JFrame main = new main();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_restaurant_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_restaurant_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_restaurant_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_restaurant_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_restaurant_information().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAddRestaraunt;
    private javax.swing.JButton jbCancel;
    private javax.swing.JComboBox jcbCategories;
    private javax.swing.JComboBox jcbStates;
    private javax.swing.JLabel jlAddress1;
    private javax.swing.JLabel jlAddress2;
    private javax.swing.JLabel jlCity;
    private javax.swing.JLabel jlFoodCategories;
    private javax.swing.JLabel jlPhone;
    private javax.swing.JLabel jlRestaurantName;
    private javax.swing.JLabel jlState;
    private javax.swing.JLabel jlZip;
    private javax.swing.JTextField jtfAddressLine1;
    private javax.swing.JTextField jtfAddressLine2;
    private javax.swing.JTextField jtfCity;
    private javax.swing.JTextField jtfPhone;
    private javax.swing.JTextField jtfRestaurantName;
    private javax.swing.JTextField jtfZip;
    // End of variables declaration//GEN-END:variables
}
