/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IST_411_GIT;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Steven
 */
public class AdvancedSearch extends javax.swing.JFrame {

    /**
     * Creates new form AdvancedSearch
     */
    public AdvancedSearch() {
        initComponents();
        String categories_result = FUNCTIONS.INTERFACE_REQUEST("1400");
        String[] categories = categories_result.split("%\\|%");
        for(int rcategory_counter = 0; rcategory_counter < categories.length; rcategory_counter++){
            String[] category_information = categories[rcategory_counter].split("\\|");
            foodCategoryAdvancedSearchComboBox.addItem(category_information[1]);
            System.out.println("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jSlider1 = new javax.swing.JSlider();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        RestaurantNameLabel = new javax.swing.JLabel();
        locationLabel = new javax.swing.JLabel();
        restaurantNameAdvancedSearchTextField = new javax.swing.JTextField();
        locationAdvancedSearchTextField = new javax.swing.JTextField();
        foodCategoryLabel = new javax.swing.JLabel();
        waitTimeLabel = new javax.swing.JLabel();
        partySizeLabel = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        foodCategoryAdvancedSearchComboBox = new javax.swing.JComboBox();
        jcb_party_size = new javax.swing.JComboBox();
        js_wait_time = new javax.swing.JSpinner();
        jb_back = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Advanced Search");

        RestaurantNameLabel.setText("Restaurant Name:");

        locationLabel.setText("Zip Code:");

        foodCategoryLabel.setText("Food Category:");

        waitTimeLabel.setText("Wait Time:");

        partySizeLabel.setText("Party Size:");

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        foodCategoryAdvancedSearchComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Food Category" }));
        foodCategoryAdvancedSearchComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodCategoryAdvancedSearchComboBoxActionPerformed(evt);
            }
        });

        jcb_party_size.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Party Size", "1-2", "3-4", "5-6", "7-10", "10+" }));

        js_wait_time.setModel(new javax.swing.SpinnerNumberModel(0, 0, 120, 5));
        js_wait_time.setRequestFocusEnabled(false);

        jb_back.setText("Back");
        jb_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(RestaurantNameLabel)
                                    .addComponent(locationLabel)
                                    .addComponent(foodCategoryLabel)
                                    .addComponent(waitTimeLabel)
                                    .addComponent(partySizeLabel))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(restaurantNameAdvancedSearchTextField)
                                    .addComponent(locationAdvancedSearchTextField)
                                    .addComponent(foodCategoryAdvancedSearchComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jcb_party_size, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(js_wait_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jb_back))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel1)))
                .addGap(58, 58, 58))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RestaurantNameLabel)
                    .addComponent(restaurantNameAdvancedSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationAdvancedSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(locationLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foodCategoryLabel)
                    .addComponent(foodCategoryAdvancedSearchComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(waitTimeLabel)
                    .addComponent(js_wait_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partySizeLabel)
                    .addComponent(jcb_party_size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton)
                    .addComponent(jb_back))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void foodCategoryAdvancedSearchComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodCategoryAdvancedSearchComboBoxActionPerformed
        
    }//GEN-LAST:event_foodCategoryAdvancedSearchComboBoxActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        String restaurant_result = FUNCTIONS.INTERFACE_REQUEST("1100","Restaurant_Name", restaurantNameAdvancedSearchTextField.getText(),"ZipCode",locationAdvancedSearchTextField.getText(),"Category",foodCategoryAdvancedSearchComboBox.getSelectedIndex()+"","Wait_Time",js_wait_time.getValue()+"","Party_Size",jcb_party_size.getSelectedIndex()+"");
        System.out.println(restaurant_result);
        if(restaurant_result.equals("") || restaurant_result.equals("<br />")){
            JOptionPane.showMessageDialog(this, "Sorry, No Restaurants were found");
        }else{
            search_results searchResults = new search_results(restaurant_result);
        }
        
        
    }//GEN-LAST:event_searchButtonActionPerformed

    private void jb_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_backActionPerformed
        JFrame main = new main();
        main.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdvancedSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdvancedSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdvancedSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdvancedSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdvancedSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RestaurantNameLabel;
    private javax.swing.JComboBox foodCategoryAdvancedSearchComboBox;
    private javax.swing.JLabel foodCategoryLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jb_back;
    private javax.swing.JComboBox jcb_party_size;
    private javax.swing.JSpinner js_wait_time;
    private javax.swing.JTextField locationAdvancedSearchTextField;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JLabel partySizeLabel;
    private javax.swing.JTextField restaurantNameAdvancedSearchTextField;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel waitTimeLabel;
    // End of variables declaration//GEN-END:variables
}
